version: '3'

services:
  virtuoso-loader:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 512M
    container_name: rdf_loader
    ports:
      - 5000:5000
    volumes:
      - ./code/app.py:/code/app.py
      - ${CONFIG_FILE}:/code/config.yaml
      - ./rdf:/web/rdf
      - ${DUMP_DIR}:/dumps
      - ${VIRTUOSO_LOG_DIR}:/logs/virtuoso
    environment:
      BASE_URL: ${BASE_URL}
      virtuoso_user: ${virtuoso_user}
      virtuoso_pswd: ${virtuoso_pswd}
      dpp2prov_api_key: ${dpp2prov_api_key}
      counter_api_key: ${counter_api_key}

networks:
  default:
    external:
      name: virtuoso_network
