version: '3'

services:
  virtuoso-loader:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: rdf_loader
    ports:
      - 5000:5000
    volumes:
      - ./code/app.py:/code/app.py
      - ./code/config.yaml:/code/config.yaml
      - ./static:/web/static
      - ${DUMP_DIR}:/dumps
      - ${VIRTUOSO_LOG_DIR}:/logs/virtuoso
