void:
  bcodmo:
    uri: 'http://www.bco-dmo.org/'
    void: 'https://www.bco-dmo.org/.well-known/void'
    triplestore:
      virtuoso:
        dump: 'local'
        path: '/dumps/bcodmo'
  lter:
    uri: 'https://www.lternet.edu/'
    void: 'https://www.bco-dmo.org/lter/void'
    triplestore:
      virtuoso:
        dump: 'local'
        path: '/dumps/lter'
triplestore:
  virtuoso:
    endpoint: 'http://ec2-34-198-164-165.compute-1.amazonaws.com:8890/sparql-auth'
    auth: 'basic'
