void:
  bcodmo:
    uri: 'http://www.bco-dmo.org/'
    void: 'https://www.bco-dmo.org/.well-known/void'
    triplestore:
      virtuoso:
        dump: 'local'
        path: '/dumps/bcodmo'
  lter:
    uri: 'urn:lternet'
    void: 'https://www.bco-dmo.org/lter/void'
    triplestore:
      virtuoso:
        dump: 'local'
        path: '/dumps/lter'
triplestore:
  virtuoso:
    endpoint: 'http://example.com/sparql-auth'
    auth: 'basic'
fileserver:
  dpp2prov:
    headers:
      name: X-API-KEY
      env: dpp2prov_api_key
  counter:
    headers:
      name: X-API-KEY
      env: counter_api_key
